"""Create User Table

Revision ID: 27f03d2cf577
Revises: f08c3273afdd
Create Date: 2025-07-26 02:35:30.226132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '27f03d2cf577'
down_revision: Union[str, Sequence[str], None] = 'f08c3273afdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User_table',
    sa.Column('ID', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('Name', sa.String(length=50), nullable=False),
    sa.Column('Phone', sa.String(length=11), nullable=False),
    sa.Column('Email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=70), nullable=False),
    sa.Column('is_admin', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('Phone')
    )
    op.create_index(op.f('ix_User_table_Email'), 'User_table', ['Email'], unique=True)
    op.create_index(op.f('ix_User_table_Name'), 'User_table', ['Name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_User_table_Name'), table_name='User_table')
    op.drop_index(op.f('ix_User_table_Email'), table_name='User_table')
    op.drop_table('User_table')
    # ### end Alembic commands ###
