"""Create Screen Table

Revision ID: e3bd6bb56a84
Revises: 7c76e6e78135
Create Date: 2025-07-26 02:57:35.967655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e3bd6bb56a84'
down_revision: Union[str, Sequence[str], None] = '7c76e6e78135'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table('Screens',
    sa.Column('ID', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('Name', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('ID'),
    sa.UniqueConstraint('Name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_table',
    sa.Column('ID', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('Name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('Phone', mysql.VARCHAR(length=11), nullable=False),
    sa.Column('Email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=70), nullable=False),
    sa.Column('is_admin', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('ID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_User_table_Name'), 'user_table', ['Name'], unique=False)
    op.create_index(op.f('ix_User_table_Email'), 'user_table', ['Email'], unique=True)
    op.create_index(op.f('Phone'), 'user_table', ['Phone'], unique=True)
    op.create_table('movie_table',
    sa.Column('ID', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('Title', mysql.VARCHAR(length=25), nullable=False),
    sa.Column('Genre', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('Duration', mysql.INTEGER(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('Language', mysql.VARCHAR(length=25), nullable=False),
    sa.Column('Rating', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('Re_Date', sa.DATE(), nullable=False),
    sa.Column('Description', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('ID', 'Title'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('Title'), 'movie_table', ['Title'], unique=True)
    op.create_index(op.f('ID'), 'movie_table', ['ID'], unique=True)
    op.drop_index(op.f('ix_User_table_Name'), table_name='User_table')
    op.drop_index(op.f('ix_User_table_Email'), table_name='User_table')
    op.drop_table('User_table')
    op.drop_table('Screens')
    op.drop_table('Movie_Table')
    # ### end Alembic commands ###
