"""Create tables

Revision ID: f1b89ba1b8f4
Revises: 
Create Date: 2025-07-23 20:29:20.918724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f1b89ba1b8f4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Movie_Table',
    sa.Column('ID', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('Title', sa.String(length=25), nullable=False),
    sa.Column('Genre', sa.String(length=20), nullable=False),
    sa.Column('Duration', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('Language', sa.String(length=25), nullable=False),
    sa.Column('Rating', sa.String(length=20), nullable=False),
    sa.Column('Re_Date', sa.DATE(), nullable=False),
    sa.Column('Description', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('ID', 'Title'),
    sa.UniqueConstraint('ID'),
    sa.UniqueConstraint('Title')
    )
    op.create_table('Screens',
    sa.Column('ID', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('Name', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('ID'),
    sa.UniqueConstraint('Name')
    )
    op.create_table('User_table',
    sa.Column('ID', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('Name', sa.String(length=50), nullable=False),
    sa.Column('Phone', sa.String(length=11), nullable=False),
    sa.Column('Email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=70), nullable=False),
    sa.Column('is_admin', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('Phone')
    )
    op.create_index(op.f('ix_User_table_Email'), 'User_table', ['Email'], unique=True)
    op.create_index(op.f('ix_User_table_Name'), 'User_table', ['Name'], unique=False)
    op.create_table('Showtime',
    sa.Column('ID', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('Movie_ID', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('Movie_name', sa.String(length=25), nullable=False),
    sa.Column('Screen_ID', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('Start_time', mysql.TIME(), nullable=False),
    sa.Column('End_time', mysql.TIME(), nullable=False),
    sa.Column('Show_date', sa.DATE(), nullable=False),
    sa.ForeignKeyConstraint(['Movie_ID'], ['Movie_Table.ID'], ),
    sa.ForeignKeyConstraint(['Movie_name'], ['Movie_Table.Title'], ),
    sa.ForeignKeyConstraint(['Screen_ID'], ['Screens.ID'], ),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('End_time'),
    sa.UniqueConstraint('ID'),
    sa.UniqueConstraint('Movie_name'),
    sa.UniqueConstraint('Start_time')
    )
    op.create_table('Reservation',
    sa.Column('ID', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('User_ID', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('Showtime_ID', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('Created_at', mysql.DATETIME(), nullable=False),
    sa.Column('Total_price', mysql.FLOAT(), nullable=False),
    sa.Column('Status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['Showtime_ID'], ['Showtime.ID'], ),
    sa.ForeignKeyConstraint(['User_ID'], ['User_table.ID'], ),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('ID')
    )
    op.create_table('Seats',
    sa.Column('ID', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('Screen_ID', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('Showtime_ID', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('Seat_number', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['Screen_ID'], ['Screens.ID'], ),
    sa.ForeignKeyConstraint(['Showtime_ID'], ['Showtime.ID'], ),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('ID')
    )
    op.create_table('Reservated_Seats',
    sa.Column('ID', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('Reservation_ID', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('Seat_ID', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('Showtime_ID', mysql.INTEGER(unsigned=True), nullable=False),
    sa.ForeignKeyConstraint(['Reservation_ID'], ['Reservation.ID'], ),
    sa.ForeignKeyConstraint(['Seat_ID'], ['Seats.ID'], ),
    sa.ForeignKeyConstraint(['Showtime_ID'], ['Showtime.ID'], ),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('ID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Reservated_Seats')
    op.drop_table('Seats')
    op.drop_table('Reservation')
    op.drop_table('Showtime')
    op.drop_index(op.f('ix_User_table_Name'), table_name='User_table')
    op.drop_index(op.f('ix_User_table_Email'), table_name='User_table')
    op.drop_table('User_table')
    op.drop_table('Screens')
    op.drop_table('Movie_Table')
    # ### end Alembic commands ###
