"""Create Multiple Table

Revision ID: f490431d8f6a
Revises: e3bd6bb56a84
Create Date: 2025-07-26 03:00:33.553577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f490431d8f6a'
down_revision: Union[str, Sequence[str], None] = 'e3bd6bb56a84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.create_table('Showtime',
    sa.Column('ID', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('Movie_name', sa.String(length=25), nullable=False),
    sa.Column('Screen_ID', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('Start_time', mysql.TIME(), nullable=False),
    sa.Column('End_time', mysql.TIME(), nullable=False),
    sa.Column('Show_date', sa.DATE(), nullable=False),
    sa.ForeignKeyConstraint(['Movie_name'], ['Movie_Table.Title'], ),
    sa.ForeignKeyConstraint(['Screen_ID'], ['Screens.ID'], ),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('End_time'),
    sa.UniqueConstraint('ID'),
    sa.UniqueConstraint('Movie_name'),
    sa.UniqueConstraint('Start_time')
    )
    op.create_table('Reservation',
    sa.Column('ID', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('User_ID', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('Showtime_ID', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('Created_at', mysql.DATETIME(), nullable=False),
    sa.Column('Total_price', mysql.FLOAT(), nullable=False),
    sa.Column('Status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['Showtime_ID'], ['Showtime.ID'], ),
    sa.ForeignKeyConstraint(['User_ID'], ['User_table.ID'], ),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('ID')
    )
    op.create_table('Seats',
    sa.Column('ID', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('Screen_ID', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('Showtime_ID', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('Seat_number', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['Screen_ID'], ['Screens.ID'], ),
    sa.ForeignKeyConstraint(['Showtime_ID'], ['Showtime.ID'], ),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('ID')
    )
    op.create_table('Reservated_Seats',
    sa.Column('ID', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('Reservation_ID', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('Seat_ID', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('Showtime_ID', mysql.INTEGER(unsigned=True), nullable=False),
    sa.ForeignKeyConstraint(['Reservation_ID'], ['Reservation.ID'], ),
    sa.ForeignKeyConstraint(['Seat_ID'], ['Seats.ID'], ),
    sa.ForeignKeyConstraint(['Showtime_ID'], ['Showtime.ID'], ),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('ID')
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie_table',
    sa.Column('ID', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('Title', mysql.VARCHAR(length=25), nullable=False),
    sa.Column('Genre', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('Duration', mysql.INTEGER(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('Language', mysql.VARCHAR(length=25), nullable=False),
    sa.Column('Rating', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('Re_Date', sa.DATE(), nullable=False),
    sa.Column('Description', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('ID', 'Title'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('Title'), 'movie_table', ['Title'], unique=True)
    op.create_index(op.f('ID'), 'movie_table', ['ID'], unique=True)
    op.create_table('screens',
    sa.Column('ID', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('Name', mysql.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('ID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('Name'), 'screens', ['Name'], unique=True)
    op.create_index(op.f('ID'), 'screens', ['ID'], unique=True)
    op.create_table('user_table',
    sa.Column('ID', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('Name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('Phone', mysql.VARCHAR(length=11), nullable=False),
    sa.Column('Email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=70), nullable=False),
    sa.Column('is_admin', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('ID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_User_table_Name'), 'user_table', ['Name'], unique=False)
    op.create_index(op.f('ix_User_table_Email'), 'user_table', ['Email'], unique=True)
    op.create_index(op.f('Phone'), 'user_table', ['Phone'], unique=True)
    op.drop_table('Reservated_Seats')
    op.drop_table('Seats')
    op.drop_table('Reservation')
    op.drop_table('Showtime')
    op.drop_index(op.f('ix_User_table_Name'), table_name='User_table')
    op.drop_index(op.f('ix_User_table_Email'), table_name='User_table')
    op.drop_table('User_table')
    op.drop_table('Screens')
    op.drop_table('Movie_Table')
    # ### end Alembic commands ###
