"""Changes in the user  table

Revision ID: 0cac8315efdc
Revises: 239d3a0a2b40
Create Date: 2025-08-09 13:04:13.222247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cac8315efdc'
down_revision: Union[str, Sequence[str], None] = '239d3a0a2b40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute('CREATE SEQUENCE user_table_id_seq OWNED BY "User_table"."ID"')

    # Set default value to use the sequence
    op.execute('ALTER TABLE "User_table" ALTER COLUMN "ID" SET DEFAULT nextval(\'user_table_id_seq\')')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Reservated_Seats', ['ID'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Reservated_Seats', type_='unique')
    # ### end Alembic commands ###
