"""Add Seats Table

Revision ID: 120ebf76a101
Revises: 1a6eeea3b7ec
Create Date: 2025-08-08 02:57:17.459861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '120ebf76a101'
down_revision: Union[str, Sequence[str], None] = '1a6eeea3b7ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Seats',
    sa.Column('ID', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Screen_ID', sa.INTEGER(), nullable=False),
    sa.Column('Showtime_ID', sa.INTEGER(), nullable=False),
    sa.Column('Seat_number', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['Screen_ID'], ['Screens.ID'], ),
    sa.ForeignKeyConstraint(['Showtime_ID'], ['Showtime.ID'], ),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('ID')
    )
    op.create_unique_constraint(None, 'Showtime', ['ID'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Showtime', type_='unique')
    op.drop_table('Seats')
    # ### end Alembic commands ###
