"""Add Showtime Table

Revision ID: 1a6eeea3b7ec
Revises: 99fc0fc5acee
Create Date: 2025-08-08 02:56:29.624753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1a6eeea3b7ec'
down_revision: Union[str, Sequence[str], None] = '99fc0fc5acee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Showtime',
    sa.Column('ID', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Movie_name', sa.String(length=25), nullable=False),
    sa.Column('Screen_ID', sa.INTEGER(), nullable=False),
    sa.Column('Start_time', postgresql.TIME(), nullable=False),
    sa.Column('End_time', postgresql.TIME(), nullable=False),
    sa.Column('Show_date', sa.DATE(), nullable=False),
    sa.ForeignKeyConstraint(['Movie_name'], ['Movie_Table.Title'], ),
    sa.ForeignKeyConstraint(['Screen_ID'], ['Screens.ID'], ),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('End_time'),
    sa.UniqueConstraint('ID'),
    sa.UniqueConstraint('Movie_name'),
    sa.UniqueConstraint('Start_time')
    )
    op.create_unique_constraint(None, 'Screens', ['ID'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Screens', type_='unique')
    op.drop_table('Showtime')
    # ### end Alembic commands ###
