"""Add Reservation_Seat Table

Revision ID: 239d3a0a2b40
Revises: 442c6f361f55
Create Date: 2025-08-08 03:17:11.788905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '239d3a0a2b40'
down_revision: Union[str, Sequence[str], None] = '442c6f361f55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Reservated_Seats',
    sa.Column('ID', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Reservation_ID', sa.INTEGER(), nullable=False),
    sa.Column('Seat_ID', sa.INTEGER(), nullable=False),
    sa.Column('Showtime_ID', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['Reservation_ID'], ['Reservation.ID'], ),
    sa.ForeignKeyConstraint(['Seat_ID'], ['Seats.ID'], ),
    sa.ForeignKeyConstraint(['Showtime_ID'], ['Showtime.ID'], ),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('ID')
    )
    op.create_unique_constraint(None, 'Reservation', ['ID'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Reservation', type_='unique')
    op.drop_table('Reservated_Seats')
    # ### end Alembic commands ###
