"""Add Reservation Table

Revision ID: 442c6f361f55
Revises: 120ebf76a101
Create Date: 2025-08-08 03:00:14.360638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '442c6f361f55'
down_revision: Union[str, Sequence[str], None] = '120ebf76a101'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Reservation',
    sa.Column('ID', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('User_ID', sa.INTEGER(), nullable=False),
    sa.Column('Showtime_ID', sa.INTEGER(), nullable=False),
    sa.Column('Created_at', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('Total_price', sa.FLOAT(), nullable=False),
    sa.Column('Status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['Showtime_ID'], ['Showtime.ID'], ),
    sa.ForeignKeyConstraint(['User_ID'], ['User_table.ID'], ),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('ID')
    )
    op.create_unique_constraint(None, 'Seats', ['ID'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Seats', type_='unique')
    op.drop_table('Reservation')
    # ### end Alembic commands ###
