"""Add Movie Table

Revision ID: f89258be7ff0
Revises: 454658656951
Create Date: 2025-08-08 02:51:02.144778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f89258be7ff0'
down_revision: Union[str, Sequence[str], None] = '454658656951'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Movie_Table',
    sa.Column('ID', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Title', sa.String(length=25), nullable=False),
    sa.Column('Genre', sa.String(length=20), nullable=False),
    sa.Column('Duration', sa.INTEGER(), nullable=False),
    sa.Column('Language', sa.String(length=25), nullable=False),
    sa.Column('Rating', sa.String(length=20), nullable=False),
    sa.Column('Re_Date', sa.DATE(), nullable=False),
    sa.Column('Description', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('ID', 'Title'),
    sa.UniqueConstraint('ID'),
    sa.UniqueConstraint('Title')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Movie_Table')
    # ### end Alembic commands ###
